version: "3"
volumes:
  wordpress:
  db:
  prometheus_data: {}
  grafana_data: {}
  app-log: {}
  db-data: {}
  prometheus-data: {}
  grafana-data: {}
networks:
  front-tier:
  back-tier:
    driver: bridge
services:
  goclient:
    build: ./goclient
    ports:
      - "80:80"
    networks:
        - back-tier
    restart: always
  server:
    build: ./server
    ports:
      - "9000:9000"
    networks:
        - back-tier
    volumes:
      - ./log:/log
    restart: always
  gateway:
    build: ./gateway
    ports:
      - "9090:9090"
    networks:
        - back-tier
    volumes:
      - ./log:/log
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    env_file:
      - ./grafana/config.monitoring
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - back-tier
      - front-tier

    restart: always
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    restart: always
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    restart: always
