version: "3"
networks:
  back-tier:
    driver: bridge
services:
  goclient:
    build: ./goclient
    ports:
      - "8080:8080"
    networks:
        - back-tier
  server:
    build: ./server
    ports:
      - "9000:9000"
    networks:
        - back-tier
  gateway:
    build: ./gateway
    ports:
      - "9090:9090"
    networks:
        - back-tier
