// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Rig.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RigResponses struct {
	Response             []string `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RigResponses) Reset()         { *m = RigResponses{} }
func (m *RigResponses) String() string { return proto.CompactTextString(m) }
func (*RigResponses) ProtoMessage()    {}
func (*RigResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a397db3166ae542, []int{0}
}

func (m *RigResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RigResponses.Unmarshal(m, b)
}
func (m *RigResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RigResponses.Marshal(b, m, deterministic)
}
func (m *RigResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RigResponses.Merge(m, src)
}
func (m *RigResponses) XXX_Size() int {
	return xxx_messageInfo_RigResponses.Size(m)
}
func (m *RigResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_RigResponses.DiscardUnknown(m)
}

var xxx_messageInfo_RigResponses proto.InternalMessageInfo

func (m *RigResponses) GetResponse() []string {
	if m != nil {
		return m.Response
	}
	return nil
}

type Rig struct {
	Nbr                  string   `protobuf:"bytes,1,opt,name=Nbr,proto3" json:"Nbr,omitempty"`
	Man                  bool     `protobuf:"varint,2,opt,name=Man,proto3" json:"Man,omitempty"`
	Woman                bool     `protobuf:"varint,3,opt,name=Woman,proto3" json:"Woman,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rig) Reset()         { *m = Rig{} }
func (m *Rig) String() string { return proto.CompactTextString(m) }
func (*Rig) ProtoMessage()    {}
func (*Rig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a397db3166ae542, []int{1}
}

func (m *Rig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rig.Unmarshal(m, b)
}
func (m *Rig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rig.Marshal(b, m, deterministic)
}
func (m *Rig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rig.Merge(m, src)
}
func (m *Rig) XXX_Size() int {
	return xxx_messageInfo_Rig.Size(m)
}
func (m *Rig) XXX_DiscardUnknown() {
	xxx_messageInfo_Rig.DiscardUnknown(m)
}

var xxx_messageInfo_Rig proto.InternalMessageInfo

func (m *Rig) GetNbr() string {
	if m != nil {
		return m.Nbr
	}
	return ""
}

func (m *Rig) GetMan() bool {
	if m != nil {
		return m.Man
	}
	return false
}

func (m *Rig) GetWoman() bool {
	if m != nil {
		return m.Woman
	}
	return false
}

func init() {
	proto.RegisterType((*RigResponses)(nil), "linuxCommand.RigResponses")
	proto.RegisterType((*Rig)(nil), "linuxCommand.Rig")
}

func init() {
	proto.RegisterFile("proto/Rig.proto", fileDescriptor_7a397db3166ae542)
}

var fileDescriptor_7a397db3166ae542 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x0f, 0xca, 0x4c, 0xd7, 0x03, 0xb3, 0x84, 0x78, 0x72, 0x32, 0xf3, 0x4a, 0x2b, 0x9c,
	0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0x94, 0xb4, 0xb8, 0x78, 0x82, 0x32, 0xd3, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x8b, 0x85, 0xa4, 0xb8, 0x38, 0x8a, 0xa0, 0x1c, 0x09, 0x46, 0x05,
	0x66, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0xc9, 0x9e, 0x8b, 0x39, 0x28, 0x33, 0x5d, 0x48, 0x80, 0x8b,
	0xd9, 0x2f, 0xa9, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x04, 0x89, 0xf8, 0x26,
	0xe6, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0xe1, 0xf9,
	0xb9, 0x89, 0x79, 0x12, 0xcc, 0x60, 0x31, 0x08, 0xc7, 0xc8, 0x9d, 0x8b, 0x2b, 0x28, 0x33, 0x3d,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x92, 0x8b, 0xcd, 0x3d, 0xb5, 0x04, 0x64, 0xa2,
	0xa0, 0x1e, 0xb2, 0x9b, 0xf4, 0x82, 0x32, 0xd3, 0xa5, 0xa4, 0x30, 0x84, 0xe0, 0x6e, 0x54, 0x62,
	0x70, 0x12, 0x88, 0xe2, 0xd3, 0xb3, 0x46, 0x56, 0x90, 0xc4, 0x06, 0xf6, 0x9c, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x00, 0x24, 0xd0, 0x63, 0xef, 0x00, 0x00, 0x00,
}
