// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Banner.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Banner struct {
	Message              []string `protobuf:"bytes,1,rep,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_514edf56ee2fab76, []int{0}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Banner)(nil), "linuxCommand.Banner")
}

func init() {
	proto.RegisterFile("proto/Banner.proto", fileDescriptor_514edf56ee2fab76)
}

var fileDescriptor_514edf56ee2fab76 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0x4a, 0xcc, 0xcb, 0x4b, 0x2d, 0xd2, 0x03, 0x73, 0x84, 0x78, 0x72, 0x32, 0xf3,
	0x4a, 0x2b, 0x9c, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0xa4, 0x44, 0x20, 0x2a, 0x82, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x21, 0x6a, 0x94, 0x94, 0xb8, 0xd8, 0x20, 0x7a, 0x84, 0x24, 0xb8,
	0xd8, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x60,
	0x5c, 0x23, 0x5f, 0x2e, 0x5e, 0x88, 0x9a, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x1b,
	0x2e, 0x4e, 0xf7, 0xd4, 0x12, 0xa8, 0x3e, 0x11, 0x3d, 0x64, 0x6b, 0xf4, 0x20, 0xa2, 0x52, 0xe2,
	0xa8, 0xa2, 0x30, 0x5b, 0x8b, 0x95, 0x18, 0x9c, 0x04, 0xa2, 0xf8, 0xf4, 0xac, 0x91, 0x65, 0x93,
	0xd8, 0xc0, 0x6e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x78, 0x02, 0xc2, 0x97, 0xc5, 0x00,
	0x00, 0x00,
}
