// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Cow.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cow struct {
	Think                bool     `protobuf:"varint,1,opt,name=Think,proto3" json:"Think,omitempty"`
	L                    bool     `protobuf:"varint,2,opt,name=L,proto3" json:"L,omitempty"`
	B                    bool     `protobuf:"varint,3,opt,name=B,proto3" json:"B,omitempty"`
	D                    bool     `protobuf:"varint,4,opt,name=D,proto3" json:"D,omitempty"`
	G                    bool     `protobuf:"varint,5,opt,name=G,proto3" json:"G,omitempty"`
	P                    bool     `protobuf:"varint,6,opt,name=P,proto3" json:"P,omitempty"`
	S                    bool     `protobuf:"varint,7,opt,name=S,proto3" json:"S,omitempty"`
	T                    bool     `protobuf:"varint,8,opt,name=T,proto3" json:"T,omitempty"`
	W                    bool     `protobuf:"varint,9,opt,name=W,proto3" json:"W,omitempty"`
	E                    string   `protobuf:"bytes,10,opt,name=E,proto3" json:"E,omitempty"`
	TT                   string   `protobuf:"bytes,11,opt,name=TT,proto3" json:"TT,omitempty"`
	F                    string   `protobuf:"bytes,12,opt,name=F,proto3" json:"F,omitempty"`
	Message              string   `protobuf:"bytes,13,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cow) Reset()         { *m = Cow{} }
func (m *Cow) String() string { return proto.CompactTextString(m) }
func (*Cow) ProtoMessage()    {}
func (*Cow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f870f85c2f993ac0, []int{0}
}

func (m *Cow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cow.Unmarshal(m, b)
}
func (m *Cow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cow.Marshal(b, m, deterministic)
}
func (m *Cow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cow.Merge(m, src)
}
func (m *Cow) XXX_Size() int {
	return xxx_messageInfo_Cow.Size(m)
}
func (m *Cow) XXX_DiscardUnknown() {
	xxx_messageInfo_Cow.DiscardUnknown(m)
}

var xxx_messageInfo_Cow proto.InternalMessageInfo

func (m *Cow) GetThink() bool {
	if m != nil {
		return m.Think
	}
	return false
}

func (m *Cow) GetL() bool {
	if m != nil {
		return m.L
	}
	return false
}

func (m *Cow) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

func (m *Cow) GetD() bool {
	if m != nil {
		return m.D
	}
	return false
}

func (m *Cow) GetG() bool {
	if m != nil {
		return m.G
	}
	return false
}

func (m *Cow) GetP() bool {
	if m != nil {
		return m.P
	}
	return false
}

func (m *Cow) GetS() bool {
	if m != nil {
		return m.S
	}
	return false
}

func (m *Cow) GetT() bool {
	if m != nil {
		return m.T
	}
	return false
}

func (m *Cow) GetW() bool {
	if m != nil {
		return m.W
	}
	return false
}

func (m *Cow) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

func (m *Cow) GetTT() string {
	if m != nil {
		return m.TT
	}
	return ""
}

func (m *Cow) GetF() string {
	if m != nil {
		return m.F
	}
	return ""
}

func (m *Cow) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Cow)(nil), "linuxCommand.Cow")
}

func init() {
	proto.RegisterFile("proto/Cow.proto", fileDescriptor_f870f85c2f993ac0)
}

var fileDescriptor_f870f85c2f993ac0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd0, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0x07, 0x70, 0x2f, 0xb5, 0x69, 0xfb, 0x8c, 0xd5, 0x9e, 0x05, 0x1f, 0x99, 0x4a, 0xa7, 0x4e,
	0x11, 0x14, 0x5c, 0x74, 0x4a, 0x9a, 0x64, 0xa9, 0x50, 0x92, 0x83, 0x82, 0x5b, 0xd5, 0x43, 0x83,
	0x4d, 0x2e, 0xf4, 0xa2, 0xd1, 0xd5, 0x6f, 0xe8, 0x37, 0x92, 0xbb, 0x47, 0xa1, 0x5d, 0xdc, 0xee,
	0xf7, 0x7f, 0xef, 0x0d, 0xf7, 0x87, 0xb3, 0x7a, 0xab, 0x1a, 0x75, 0x15, 0xa9, 0x36, 0xb0, 0x2f,
	0xee, 0x6d, 0x8a, 0xea, 0xe3, 0x2b, 0x52, 0x65, 0xb9, 0xae, 0x5e, 0xfc, 0x31, 0x8d, 0x33, 0xa9,
	0x6b, 0x55, 0x69, 0x49, 0x3b, 0xfe, 0x88, 0xd2, 0xb8, 0xac, 0x9b, 0x6f, 0x8a, 0xa6, 0xbf, 0x0c,
	0x3a, 0x91, 0x6a, 0xf9, 0x18, 0xba, 0xe2, 0xad, 0xa8, 0xde, 0x91, 0x4d, 0xd8, 0xac, 0x9f, 0x11,
	0xb8, 0x07, 0x6c, 0x81, 0x8e, 0x4d, 0xd8, 0xc2, 0x28, 0xc4, 0x0e, 0x29, 0x34, 0x9a, 0xe3, 0x31,
	0x69, 0x6e, 0x94, 0x62, 0x97, 0x94, 0x1a, 0x2d, 0xd1, 0x25, 0x2d, 0x8d, 0x72, 0xec, 0x91, 0x72,
	0x23, 0x81, 0x7d, 0x92, 0x30, 0x5a, 0xe1, 0x80, 0xb4, 0x32, 0x8a, 0x11, 0x26, 0x6c, 0x36, 0xc8,
	0x58, 0xcc, 0x87, 0xe0, 0x08, 0x81, 0x27, 0x96, 0x8e, 0xb0, 0xbb, 0x09, 0x7a, 0x34, 0x4d, 0x38,
	0x42, 0xef, 0x41, 0x6a, 0xbd, 0x7e, 0x95, 0x78, 0x6a, 0xb3, 0x1d, 0xaf, 0x7f, 0x18, 0x40, 0xa4,
	0xda, 0x5c, 0x6e, 0x3f, 0x8b, 0x67, 0xc9, 0x6f, 0xc1, 0x4d, 0x65, 0x63, 0x3e, 0x39, 0x0a, 0xf6,
	0x4b, 0x0a, 0x22, 0xd5, 0xfa, 0x97, 0x87, 0xd1, 0xae, 0x30, 0x3d, 0x3d, 0xe2, 0xf7, 0x00, 0x74,
	0x97, 0x14, 0x1b, 0xc9, 0x2f, 0x0e, 0x17, 0x6d, 0x87, 0xff, 0x5c, 0x87, 0xe7, 0x8f, 0xc3, 0xe0,
	0x6e, 0x7f, 0xfa, 0xe4, 0xda, 0xc6, 0x6f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xe3, 0x18,
	0xd7, 0xbb, 0x01, 0x00, 0x00,
}
