// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Empty.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	Z                    bool     `protobuf:"varint,1,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7f8f683bfecaf03, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetZ() bool {
	if m != nil {
		return m.Z
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "linuxCommand.Empty")
}

func init() {
	proto.RegisterFile("proto/Empty.proto", fileDescriptor_e7f8f683bfecaf03)
}

var fileDescriptor_e7f8f683bfecaf03 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x77, 0xcd, 0x2d, 0x28, 0xa9, 0xd4, 0x03, 0xb3, 0x85, 0x78, 0x72, 0x32, 0xf3, 0x4a,
	0x2b, 0x9c, 0xf3, 0x73, 0x73, 0x13, 0xf3, 0x52, 0x94, 0x44, 0xb9, 0x58, 0xc1, 0x92, 0x42, 0x3c,
	0x5c, 0x8c, 0x51, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x8c, 0x51, 0x4e, 0x02, 0x51, 0x7c,
	0x7a, 0xd6, 0xc8, 0x0a, 0x93, 0xd8, 0xc0, 0xba, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xfd, 0x5e, 0xdf, 0x52, 0x00, 0x00, 0x00,
}
