// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/figlet.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Figlet struct {
	R                    bool     `protobuf:"varint,1,opt,name=R,proto3" json:"R,omitempty"`
	X                    bool     `protobuf:"varint,2,opt,name=X,proto3" json:"X,omitempty"`
	L                    bool     `protobuf:"varint,3,opt,name=L,proto3" json:"L,omitempty"`
	RR                   bool     `protobuf:"varint,4,opt,name=RR,proto3" json:"RR,omitempty"`
	XX                   bool     `protobuf:"varint,5,opt,name=XX,proto3" json:"XX,omitempty"`
	LL                   bool     `protobuf:"varint,6,opt,name=LL,proto3" json:"LL,omitempty"`
	C                    bool     `protobuf:"varint,7,opt,name=C,proto3" json:"C,omitempty"`
	P                    bool     `protobuf:"varint,8,opt,name=P,proto3" json:"P,omitempty"`
	N                    bool     `protobuf:"varint,9,opt,name=N,proto3" json:"N,omitempty"`
	O                    bool     `protobuf:"varint,10,opt,name=O,proto3" json:"O,omitempty"`
	W                    bool     `protobuf:"varint,11,opt,name=W,proto3" json:"W,omitempty"`
	K                    bool     `protobuf:"varint,12,opt,name=K,proto3" json:"K,omitempty"`
	S                    bool     `protobuf:"varint,13,opt,name=S,proto3" json:"S,omitempty"`
	SS                   bool     `protobuf:"varint,14,opt,name=SS,proto3" json:"SS,omitempty"`
	NN                   bool     `protobuf:"varint,15,opt,name=NN,proto3" json:"NN,omitempty"`
	E                    bool     `protobuf:"varint,16,opt,name=E,proto3" json:"E,omitempty"`
	D                    bool     `protobuf:"varint,17,opt,name=D,proto3" json:"D,omitempty"`
	T                    bool     `protobuf:"varint,18,opt,name=T,proto3" json:"T,omitempty"`
	NNN                  bool     `protobuf:"varint,19,opt,name=NNN,proto3" json:"NNN,omitempty"`
	WW                   string   `protobuf:"bytes,20,opt,name=WW,proto3" json:"WW,omitempty"`
	M                    string   `protobuf:"bytes,21,opt,name=M,proto3" json:"M,omitempty"`
	F                    string   `protobuf:"bytes,22,opt,name=F,proto3" json:"F,omitempty"`
	CC                   string   `protobuf:"bytes,23,opt,name=CC,proto3" json:"CC,omitempty"`
	Message              string   `protobuf:"bytes,24,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Figlet) Reset()         { *m = Figlet{} }
func (m *Figlet) String() string { return proto.CompactTextString(m) }
func (*Figlet) ProtoMessage()    {}
func (*Figlet) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c2c9a5b3d755601, []int{0}
}

func (m *Figlet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Figlet.Unmarshal(m, b)
}
func (m *Figlet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Figlet.Marshal(b, m, deterministic)
}
func (m *Figlet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Figlet.Merge(m, src)
}
func (m *Figlet) XXX_Size() int {
	return xxx_messageInfo_Figlet.Size(m)
}
func (m *Figlet) XXX_DiscardUnknown() {
	xxx_messageInfo_Figlet.DiscardUnknown(m)
}

var xxx_messageInfo_Figlet proto.InternalMessageInfo

func (m *Figlet) GetR() bool {
	if m != nil {
		return m.R
	}
	return false
}

func (m *Figlet) GetX() bool {
	if m != nil {
		return m.X
	}
	return false
}

func (m *Figlet) GetL() bool {
	if m != nil {
		return m.L
	}
	return false
}

func (m *Figlet) GetRR() bool {
	if m != nil {
		return m.RR
	}
	return false
}

func (m *Figlet) GetXX() bool {
	if m != nil {
		return m.XX
	}
	return false
}

func (m *Figlet) GetLL() bool {
	if m != nil {
		return m.LL
	}
	return false
}

func (m *Figlet) GetC() bool {
	if m != nil {
		return m.C
	}
	return false
}

func (m *Figlet) GetP() bool {
	if m != nil {
		return m.P
	}
	return false
}

func (m *Figlet) GetN() bool {
	if m != nil {
		return m.N
	}
	return false
}

func (m *Figlet) GetO() bool {
	if m != nil {
		return m.O
	}
	return false
}

func (m *Figlet) GetW() bool {
	if m != nil {
		return m.W
	}
	return false
}

func (m *Figlet) GetK() bool {
	if m != nil {
		return m.K
	}
	return false
}

func (m *Figlet) GetS() bool {
	if m != nil {
		return m.S
	}
	return false
}

func (m *Figlet) GetSS() bool {
	if m != nil {
		return m.SS
	}
	return false
}

func (m *Figlet) GetNN() bool {
	if m != nil {
		return m.NN
	}
	return false
}

func (m *Figlet) GetE() bool {
	if m != nil {
		return m.E
	}
	return false
}

func (m *Figlet) GetD() bool {
	if m != nil {
		return m.D
	}
	return false
}

func (m *Figlet) GetT() bool {
	if m != nil {
		return m.T
	}
	return false
}

func (m *Figlet) GetNNN() bool {
	if m != nil {
		return m.NNN
	}
	return false
}

func (m *Figlet) GetWW() string {
	if m != nil {
		return m.WW
	}
	return ""
}

func (m *Figlet) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

func (m *Figlet) GetF() string {
	if m != nil {
		return m.F
	}
	return ""
}

func (m *Figlet) GetCC() string {
	if m != nil {
		return m.CC
	}
	return ""
}

func (m *Figlet) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Figlet)(nil), "linuxCommand.Figlet")
}

func init() {
	proto.RegisterFile("proto/figlet.proto", fileDescriptor_1c2c9a5b3d755601)
}

var fileDescriptor_1c2c9a5b3d755601 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x07, 0x70, 0xb7, 0x28, 0x1f, 0x2b, 0x20, 0x2c, 0x28, 0x13, 0x4e, 0x84, 0x13, 0xa7, 0x9a,
	0xe8, 0x51, 0x13, 0x13, 0x17, 0xea, 0x81, 0xb2, 0x90, 0x2d, 0x49, 0x1b, 0x6f, 0xa8, 0x2b, 0x69,
	0x02, 0xb4, 0xa1, 0xd5, 0xe8, 0x4b, 0xf8, 0xb8, 0x9e, 0xcd, 0xec, 0x88, 0x81, 0x8b, 0xb7, 0xfe,
	0xa6, 0xff, 0x99, 0x6d, 0x3a, 0xcb, 0x45, 0xba, 0x4d, 0xf2, 0xe4, 0xf2, 0x35, 0x5e, 0xae, 0x4c,
	0xee, 0x5a, 0x88, 0xea, 0x2a, 0xde, 0xbc, 0x7d, 0xc8, 0x64, 0xbd, 0x5e, 0x6c, 0x5e, 0xba, 0x4d,
	0x4a, 0x8c, 0xd6, 0x69, 0xfe, 0x49, 0x81, 0x6e, 0x9b, 0x4a, 0xda, 0x64, 0x69, 0xb2, 0xc9, 0x0c,
	0x55, 0xfb, 0xdf, 0x0e, 0x2f, 0x7a, 0x76, 0x8e, 0xa8, 0x72, 0xa6, 0x81, 0xf5, 0xd8, 0xa0, 0xac,
	0x99, 0x46, 0x45, 0xe0, 0x90, 0x22, 0x94, 0x0f, 0x05, 0x92, 0x2f, 0xea, 0xdc, 0xd1, 0x1a, 0x8e,
	0x2d, 0x1d, 0xad, 0xd1, 0x51, 0x04, 0x27, 0xe4, 0x28, 0x42, 0xfb, 0x3e, 0x14, 0xc9, 0xbe, 0x8f,
	0xdd, 0x12, 0x4a, 0xd4, 0x2d, 0x51, 0x33, 0x28, 0x93, 0x66, 0x28, 0x05, 0x15, 0x92, 0x42, 0x4d,
	0x81, 0x93, 0xa6, 0xa8, 0x10, 0x4e, 0x49, 0x21, 0x6a, 0x0c, 0x55, 0xd2, 0x18, 0x15, 0x40, 0x8d,
	0x14, 0xe0, 0x89, 0x41, 0x00, 0x75, 0x3a, 0x31, 0xb0, 0x56, 0x0a, 0xce, 0xc8, 0xca, 0xce, 0x1d,
	0x41, 0x83, 0xd2, 0x23, 0xd4, 0x10, 0x9a, 0xa4, 0x21, 0x6a, 0x0e, 0x82, 0x34, 0x17, 0x0d, 0x5e,
	0x50, 0x4a, 0x41, 0xcb, 0x1a, 0x1f, 0x71, 0x56, 0x18, 0x42, 0xbb, 0xc7, 0x06, 0x15, 0xed, 0x84,
	0xf6, 0x3b, 0x26, 0x70, 0x6e, 0xc9, 0x26, 0x28, 0x0f, 0x2e, 0x48, 0x1e, 0x66, 0xa5, 0x84, 0x0e,
	0x65, 0xa5, 0x14, 0xc0, 0x4b, 0x13, 0x93, 0x65, 0x8b, 0xa5, 0x01, 0xb0, 0xc5, 0x1d, 0xaf, 0xbe,
	0x18, 0xaf, 0xd1, 0x8f, 0x0f, 0xcc, 0xf6, 0x3d, 0x7e, 0x36, 0xe2, 0x96, 0x57, 0x1e, 0x4c, 0xfe,
	0xbb, 0x8c, 0xb6, 0xbb, 0xbf, 0x4f, 0x97, 0xaa, 0xdd, 0xce, 0x61, 0x75, 0xb7, 0xcb, 0xac, 0x7f,
	0x24, 0xee, 0x78, 0xed, 0xaf, 0xdb, 0x8b, 0x57, 0x46, 0xb4, 0x0e, 0xb3, 0xf6, 0x2a, 0xfc, 0x33,
	0xe0, 0xbe, 0xf1, 0x58, 0x77, 0x6f, 0xf6, 0xdf, 0x3e, 0x15, 0xed, 0x15, 0xb9, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xdb, 0x79, 0xf8, 0xf0, 0x6f, 0x02, 0x00, 0x00,
}
