// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/Fortune.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Percent struct {
	Percent              string   `protobuf:"bytes,1,opt,name=Percent,proto3" json:"Percent,omitempty"`
	Fortune              string   `protobuf:"bytes,2,opt,name=fortune,proto3" json:"fortune,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Percent) Reset()         { *m = Percent{} }
func (m *Percent) String() string { return proto.CompactTextString(m) }
func (*Percent) ProtoMessage()    {}
func (*Percent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbdc3dd144b4f12e, []int{0}
}

func (m *Percent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Percent.Unmarshal(m, b)
}
func (m *Percent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Percent.Marshal(b, m, deterministic)
}
func (m *Percent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Percent.Merge(m, src)
}
func (m *Percent) XXX_Size() int {
	return xxx_messageInfo_Percent.Size(m)
}
func (m *Percent) XXX_DiscardUnknown() {
	xxx_messageInfo_Percent.DiscardUnknown(m)
}

var xxx_messageInfo_Percent proto.InternalMessageInfo

func (m *Percent) GetPercent() string {
	if m != nil {
		return m.Percent
	}
	return ""
}

func (m *Percent) GetFortune() string {
	if m != nil {
		return m.Fortune
	}
	return ""
}

type Fortune struct {
	A                    bool       `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	C                    bool       `protobuf:"varint,2,opt,name=C,proto3" json:"C,omitempty"`
	E                    bool       `protobuf:"varint,3,opt,name=E,proto3" json:"E,omitempty"`
	F                    bool       `protobuf:"varint,4,opt,name=F,proto3" json:"F,omitempty"`
	L                    bool       `protobuf:"varint,5,opt,name=L,proto3" json:"L,omitempty"`
	O                    bool       `protobuf:"varint,6,opt,name=O,proto3" json:"O,omitempty"`
	S                    bool       `protobuf:"varint,7,opt,name=S,proto3" json:"S,omitempty"`
	I                    bool       `protobuf:"varint,8,opt,name=I,proto3" json:"I,omitempty"`
	U                    bool       `protobuf:"varint,9,opt,name=U,proto3" json:"U,omitempty"`
	M                    string     `protobuf:"bytes,10,opt,name=M,proto3" json:"M,omitempty"`
	N                    string     `protobuf:"bytes,11,opt,name=N,proto3" json:"N,omitempty"`
	Percent              []*Percent `protobuf:"bytes,12,rep,name=Percent,proto3" json:"Percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Fortune) Reset()         { *m = Fortune{} }
func (m *Fortune) String() string { return proto.CompactTextString(m) }
func (*Fortune) ProtoMessage()    {}
func (*Fortune) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbdc3dd144b4f12e, []int{1}
}

func (m *Fortune) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fortune.Unmarshal(m, b)
}
func (m *Fortune) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fortune.Marshal(b, m, deterministic)
}
func (m *Fortune) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fortune.Merge(m, src)
}
func (m *Fortune) XXX_Size() int {
	return xxx_messageInfo_Fortune.Size(m)
}
func (m *Fortune) XXX_DiscardUnknown() {
	xxx_messageInfo_Fortune.DiscardUnknown(m)
}

var xxx_messageInfo_Fortune proto.InternalMessageInfo

func (m *Fortune) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

func (m *Fortune) GetC() bool {
	if m != nil {
		return m.C
	}
	return false
}

func (m *Fortune) GetE() bool {
	if m != nil {
		return m.E
	}
	return false
}

func (m *Fortune) GetF() bool {
	if m != nil {
		return m.F
	}
	return false
}

func (m *Fortune) GetL() bool {
	if m != nil {
		return m.L
	}
	return false
}

func (m *Fortune) GetO() bool {
	if m != nil {
		return m.O
	}
	return false
}

func (m *Fortune) GetS() bool {
	if m != nil {
		return m.S
	}
	return false
}

func (m *Fortune) GetI() bool {
	if m != nil {
		return m.I
	}
	return false
}

func (m *Fortune) GetU() bool {
	if m != nil {
		return m.U
	}
	return false
}

func (m *Fortune) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

func (m *Fortune) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

func (m *Fortune) GetPercent() []*Percent {
	if m != nil {
		return m.Percent
	}
	return nil
}

type Empty struct {
	Z                    bool     `protobuf:"varint,1,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbdc3dd144b4f12e, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetZ() bool {
	if m != nil {
		return m.Z
	}
	return false
}

func init() {
	proto.RegisterType((*Percent)(nil), "linuxCommand.Percent")
	proto.RegisterType((*Fortune)(nil), "linuxCommand.Fortune")
	proto.RegisterType((*Empty)(nil), "linuxCommand.Empty")
}

func init() {
	proto.RegisterFile("proto/Fortune.proto", fileDescriptor_cbdc3dd144b4f12e)
}

var fileDescriptor_cbdc3dd144b4f12e = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x07, 0x70, 0xd7, 0xda, 0xaf, 0x6d, 0x08, 0xb2, 0xb5, 0x38, 0xf4, 0x54, 0x72, 0xea, 0x29,
	0x85, 0x7a, 0x14, 0xc5, 0x1a, 0x12, 0x29, 0xf4, 0x43, 0x12, 0x7a, 0xc9, 0x4d, 0xeb, 0x0a, 0x81,
	0xe6, 0x83, 0x24, 0x15, 0x7d, 0x0d, 0x9f, 0xcd, 0x07, 0x92, 0xd9, 0xd9, 0xb4, 0xa9, 0x07, 0x6f,
	0xf9, 0xed, 0xcc, 0x4e, 0xf6, 0xbf, 0xcb, 0xfb, 0x59, 0x9e, 0x96, 0xe9, 0xc4, 0x4b, 0xf3, 0x72,
	0x9f, 0x48, 0x5b, 0x49, 0x18, 0xbb, 0x28, 0xd9, 0x7f, 0x3a, 0x69, 0x1c, 0xbf, 0x24, 0x6f, 0xc3,
	0x2b, 0x6a, 0xf1, 0x65, 0x91, 0xa5, 0x49, 0xa1, 0x7b, 0xac, 0x3b, 0xde, 0x7e, 0x96, 0xf9, 0x56,
	0x26, 0xa5, 0x80, 0xc3, 0x27, 0xb0, 0x11, 0x1b, 0x77, 0xfd, 0x7a, 0xe5, 0x9d, 0x26, 0xc3, 0x39,
	0x55, 0x34, 0xad, 0x1f, 0xc6, 0xdb, 0xfa, 0xa7, 0xc2, 0xe0, 0x6c, 0xa6, 0x76, 0x76, 0x7c, 0x36,
	0x43, 0x39, 0xaa, 0xbb, 0xe3, 0x33, 0x07, 0xe5, 0x42, 0x83, 0xe4, 0xa2, 0x3c, 0xb8, 0x20, 0x79,
	0xa8, 0x05, 0x34, 0x49, 0x0b, 0xd4, 0x1a, 0x5a, 0xa4, 0x35, 0x2a, 0x80, 0x36, 0x29, 0x40, 0xcd,
	0xa1, 0x43, 0x9a, 0xa3, 0x36, 0xd0, 0x25, 0x6d, 0x50, 0x4b, 0xe0, 0xea, 0x74, 0x6c, 0x89, 0x5a,
	0x41, 0x8f, 0xb4, 0x12, 0x93, 0x63, 0x32, 0x63, 0xd4, 0x18, 0xf7, 0xa6, 0x03, 0xbb, 0x7e, 0x35,
	0xb6, 0x2e, 0x1e, 0x02, 0x5b, 0x03, 0xde, 0x74, 0xe3, 0xac, 0xfc, 0xc2, 0x39, 0x61, 0x95, 0x29,
	0x9c, 0x7e, 0x33, 0x6e, 0xea, 0xb4, 0x81, 0xcc, 0x3f, 0xa2, 0xad, 0x14, 0xf7, 0x9c, 0x3f, 0xc9,
	0xb2, 0xba, 0x82, 0x3f, 0x73, 0xf5, 0xf2, 0xf0, 0xfa, 0x74, 0xb9, 0x7a, 0x82, 0xc2, 0x3a, 0x13,
	0x0f, 0xdc, 0x3c, 0xee, 0xf7, 0xa2, 0x9d, 0x14, 0xfd, 0xd3, 0x66, 0x75, 0x8e, 0x7f, 0x26, 0x3c,
	0x5e, 0x86, 0xa6, 0x7d, 0x5b, 0xaf, 0xbe, 0xb6, 0xd4, 0xd3, 0xde, 0xfc, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x8e, 0x31, 0x18, 0x15, 0x02, 0x00, 0x00,
}
