// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/toilet.proto

package linuxCommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Toilet struct {
	S                    bool     `protobuf:"varint,1,opt,name=S,proto3" json:"S,omitempty"`
	SS                   bool     `protobuf:"varint,2,opt,name=SS,proto3" json:"SS,omitempty"`
	K                    bool     `protobuf:"varint,3,opt,name=K,proto3" json:"K,omitempty"`
	W                    bool     `protobuf:"varint,4,opt,name=W,proto3" json:"W,omitempty"`
	O                    bool     `protobuf:"varint,5,opt,name=O,proto3" json:"O,omitempty"`
	F                    string   `protobuf:"bytes,6,opt,name=F,proto3" json:"F,omitempty"`
	FF                   string   `protobuf:"bytes,7,opt,name=FF,proto3" json:"FF,omitempty"`
	FFF                  string   `protobuf:"bytes,8,opt,name=FFF,proto3" json:"FFF,omitempty"`
	E                    string   `protobuf:"bytes,9,opt,name=E,proto3" json:"E,omitempty"`
	F3                   string   `protobuf:"bytes,10,opt,name=F3,proto3" json:"F3,omitempty"`
	F4                   string   `protobuf:"bytes,11,opt,name=F4,proto3" json:"F4,omitempty"`
	F5                   string   `protobuf:"bytes,12,opt,name=F5,proto3" json:"F5,omitempty"`
	F6                   string   `protobuf:"bytes,13,opt,name=F6,proto3" json:"F6,omitempty"`
	F7                   string   `protobuf:"bytes,14,opt,name=F7,proto3" json:"F7,omitempty"`
	F8                   string   `protobuf:"bytes,15,opt,name=F8,proto3" json:"F8,omitempty"`
	F9                   string   `protobuf:"bytes,16,opt,name=F9,proto3" json:"F9,omitempty"`
	Message              string   `protobuf:"bytes,117,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Toilet) Reset()         { *m = Toilet{} }
func (m *Toilet) String() string { return proto.CompactTextString(m) }
func (*Toilet) ProtoMessage()    {}
func (*Toilet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2f7adcbf5a8a08a, []int{0}
}

func (m *Toilet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Toilet.Unmarshal(m, b)
}
func (m *Toilet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Toilet.Marshal(b, m, deterministic)
}
func (m *Toilet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Toilet.Merge(m, src)
}
func (m *Toilet) XXX_Size() int {
	return xxx_messageInfo_Toilet.Size(m)
}
func (m *Toilet) XXX_DiscardUnknown() {
	xxx_messageInfo_Toilet.DiscardUnknown(m)
}

var xxx_messageInfo_Toilet proto.InternalMessageInfo

func (m *Toilet) GetS() bool {
	if m != nil {
		return m.S
	}
	return false
}

func (m *Toilet) GetSS() bool {
	if m != nil {
		return m.SS
	}
	return false
}

func (m *Toilet) GetK() bool {
	if m != nil {
		return m.K
	}
	return false
}

func (m *Toilet) GetW() bool {
	if m != nil {
		return m.W
	}
	return false
}

func (m *Toilet) GetO() bool {
	if m != nil {
		return m.O
	}
	return false
}

func (m *Toilet) GetF() string {
	if m != nil {
		return m.F
	}
	return ""
}

func (m *Toilet) GetFF() string {
	if m != nil {
		return m.FF
	}
	return ""
}

func (m *Toilet) GetFFF() string {
	if m != nil {
		return m.FFF
	}
	return ""
}

func (m *Toilet) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

func (m *Toilet) GetF3() string {
	if m != nil {
		return m.F3
	}
	return ""
}

func (m *Toilet) GetF4() string {
	if m != nil {
		return m.F4
	}
	return ""
}

func (m *Toilet) GetF5() string {
	if m != nil {
		return m.F5
	}
	return ""
}

func (m *Toilet) GetF6() string {
	if m != nil {
		return m.F6
	}
	return ""
}

func (m *Toilet) GetF7() string {
	if m != nil {
		return m.F7
	}
	return ""
}

func (m *Toilet) GetF8() string {
	if m != nil {
		return m.F8
	}
	return ""
}

func (m *Toilet) GetF9() string {
	if m != nil {
		return m.F9
	}
	return ""
}

func (m *Toilet) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Toilet)(nil), "linuxCommand.Toilet")
}

func init() {
	proto.RegisterFile("proto/toilet.proto", fileDescriptor_c2f7adcbf5a8a08a)
}

var fileDescriptor_c2f7adcbf5a8a08a = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0x4b, 0x4b, 0xf3, 0x40,
	0x14, 0x06, 0xe0, 0x6f, 0xa6, 0x9f, 0xbd, 0x8c, 0x6d, 0x5a, 0xc7, 0x82, 0x87, 0xae, 0x4a, 0x57,
	0x5d, 0x45, 0x30, 0xbd, 0xa2, 0x0b, 0x2f, 0x64, 0x5c, 0x14, 0x29, 0x64, 0x84, 0x82, 0xbb, 0xaa,
	0x83, 0x04, 0x72, 0xa3, 0x49, 0x45, 0xff, 0x87, 0x0b, 0x7f, 0xae, 0xcc, 0x99, 0xa9, 0xa4, 0x3b,
	0xe9, 0xae, 0xcf, 0x7b, 0xde, 0x1e, 0xc2, 0x49, 0x18, 0xcf, 0x36, 0x69, 0x91, 0x9e, 0x17, 0x69,
	0x18, 0xa9, 0xc2, 0x45, 0xf0, 0x66, 0x14, 0x26, 0xdb, 0x8f, 0xbb, 0x34, 0x8e, 0xd7, 0xc9, 0x6b,
	0xef, 0xc4, 0x34, 0xfc, 0x38, 0x2b, 0x3e, 0x4d, 0xa1, 0xd7, 0x35, 0x51, 0xa0, 0xf2, 0x2c, 0x4d,
	0x72, 0x65, 0xd2, 0xc1, 0x37, 0x65, 0xd5, 0x47, 0xdc, 0xc3, 0x9b, 0x8c, 0x48, 0x20, 0x7d, 0x32,
	0xac, 0x07, 0x44, 0x72, 0x87, 0x51, 0x29, 0x81, 0x22, 0xa9, 0x94, 0x7a, 0xba, 0x80, 0x8a, 0x99,
	0x2e, 0xb4, 0x56, 0xf0, 0xdf, 0x68, 0xa5, 0xb5, 0x84, 0x23, 0xa3, 0xa5, 0x96, 0x80, 0x6a, 0x9f,
	0x0c, 0x1b, 0x01, 0x11, 0x7a, 0x8f, 0x10, 0x50, 0x43, 0x52, 0x21, 0x78, 0x87, 0x55, 0x84, 0x10,
	0x50, 0xc7, 0x40, 0xff, 0xd4, 0x7d, 0x1f, 0x1a, 0xa6, 0xef, 0x63, 0xdf, 0x03, 0x66, 0xfb, 0x1e,
	0x7a, 0x04, 0xc7, 0xd6, 0x23, 0xf4, 0x18, 0x9a, 0xd6, 0x63, 0xf4, 0x04, 0x5a, 0xd6, 0x13, 0xf4,
	0x14, 0x1c, 0xeb, 0x29, 0x7a, 0x06, 0x6d, 0xeb, 0x19, 0x7a, 0x0e, 0x1d, 0xeb, 0x39, 0x07, 0x56,
	0x7b, 0x50, 0x79, 0xbe, 0x7e, 0x53, 0xb0, 0xc5, 0x70, 0xc7, 0x8b, 0x2f, 0xca, 0x5a, 0xe6, 0x34,
	0x52, 0x6d, 0xde, 0xc3, 0x17, 0xc5, 0xaf, 0x58, 0xe3, 0x5e, 0x15, 0xf6, 0x5c, 0x5d, 0xb7, 0x7c,
	0x71, 0xd7, 0xa4, 0xbd, 0xb3, 0xfd, 0x74, 0x77, 0xed, 0x7c, 0xf0, 0x8f, 0x5f, 0x33, 0xe7, 0xf7,
	0xdf, 0x42, 0x84, 0x91, 0xe2, 0xa7, 0xfb, 0x65, 0x7c, 0x5b, 0x7f, 0xdd, 0xe0, 0x1f, 0xb4, 0xe1,
	0x86, 0xb5, 0x4b, 0xcf, 0x70, 0xc8, 0x8a, 0xdb, 0xce, 0x93, 0xe3, 0x5e, 0x96, 0xa7, 0xcf, 0x55,
	0xfc, 0x94, 0xbc, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd1, 0x9b, 0xec, 0x97, 0x02, 0x00,
	0x00,
}
