package linuxCommand

type Server struct {
	UnimplementedRigServiceServer
	UnimplementedFortuneServiceServer
	UnimplementedCowServiceServer
	UnimplementedFigletServiceServer
	UnimplementedToiletServiceServer
	UnimplementedXkcdpassServiceServer
}
