{
 "title": "wsk",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "total websocket session",
   "type": "graph",
   "description": "The total number of web socket sessions since server starts",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_total_sessions" }
   ]
  },
  {
   "title": "number of CRUD count",
   "type": "stat",
   "description": "The number of CRUD operations by type",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "wsk_db_crud_count" }
   ]
  },
  {
   "title": "remind password endpoint call total number",
   "type": "stat",
   "description": "The total number of calls to the remind password endpoint",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wsk_security_remindpassword_count"
    }
   ]
  },
  {
   "title": "total websocket session",
   "type": "stat",
   "description": "The total number of web socket sessions since server starts",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_total_sessions" }
   ]
  },
  {
   "title": "hr query errors total number since server start",
   "type": "stat",
   "description": "The total number of hr query errors since the server start",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_stats_errors_count" }
   ]
  },
  {
   "title": "number of CRUD count",
   "type": "graph",
   "description": "The number of CRUD operations by type",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_db_crud_count" }
   ]
  },
  {
   "title": "skill category nodes number  currently in memory",
   "type": "stat",
   "description": "The number of skill category nodes currently in memory",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wsk_stats_skillcategories_count"
    }
   ]
  },
  {
   "title": "hr number  queries received since server start",
   "type": "stat",
   "description": "The total number of hr queries received since the server start",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_stats_total_queries" }
   ]
  },
  {
   "title": "total call number of the data store (db and cache)",
   "type": "stat",
   "description": "The total number of calls to the data store (database or cache)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_store_hits_count" }
   ]
  },
  {
   "title": "total websocket error",
   "type": "stat",
   "description": "The total number of web socket errors since server starts",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_total_errors" }
   ]
  },
  {
   "title": "remind password endpoint call total number",
   "type": "graph",
   "description": "The total number of calls to the remind password endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wsk_security_remindpassword_count"
    }
   ]
  },
  {
   "title": "total db call count",
   "type": "stat",
   "description": "The total number of calls to the database",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_db_hits_count" }
   ]
  },
  {
   "title": "total byte send by websocket",
   "type": "stat",
   "description": "The total number of bytes sent through web socket",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_total_sent_bytes" }
   ]
  },
  {
   "title": "hr query errors total number since server start",
   "type": "graph",
   "description": "The total number of hr query errors since the server start",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_errors_count" }
   ]
  },
  {
   "title": "total websocket message received",
   "type": "stat",
   "description": "The total number of messages received through web socket since server starts",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_total_received_messages" }
   ]
  },
  {
   "title": "total websocket byte received",
   "type": "stat",
   "description": "The total number of bytes received through web socket",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_total_received_bytes" }
   ]
  },
  {
   "title": "currently active websocket session",
   "type": "stat",
   "description": "The number of currently active web socket sessions",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wsk_ws_active_sessions" }
   ]
  },
  {
   "title": "hr number  queries received since server start",
   "type": "graph",
   "description": "The total number of hr queries received since the server start",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_total_queries" }
   ]
  },
  {
   "title": "skill category nodes number  currently in memory",
   "type": "graph",
   "description": "The number of skill category nodes currently in memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wsk_stats_skillcategories_count"
    }
   ]
  },
  {
   "title": "total call number of the data store (db and cache)",
   "type": "graph",
   "description": "The total number of calls to the data store (database or cache)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_store_hits_count" }
   ]
  },
  {
   "title": "total websocket error",
   "type": "graph",
   "description": "The total number of web socket errors since server starts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_total_errors" }
   ]
  },
  {
   "title": "total db call count",
   "type": "graph",
   "description": "The total number of calls to the database",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_db_hits_count" }
   ]
  },
  {
   "title": "total byte send by websocket",
   "type": "graph",
   "description": "The total number of bytes sent through web socket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_total_sent_bytes" }
   ]
  },
  {
   "title": "total websocket message received",
   "type": "graph",
   "description": "The total number of messages received through web socket since server starts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_total_received_messages" }
   ]
  },
  {
   "title": "total websocket byte received",
   "type": "graph",
   "description": "The total number of bytes received through web socket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_total_received_bytes" }
   ]
  },
  {
   "title": "currently active websocket session",
   "type": "graph",
   "description": "The number of currently active web socket sessions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_ws_active_sessions" }
   ]
  },
  {
   "title": "total unit nodes currently in memory",
   "type": "graph",
   "description": "The number of unit nodes currently in memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_units_count" }
   ]
  },
  {
   "title": "number nodes skills currently in memory",
   "type": "graph",
   "description": "The number of skill nodes currently in memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_skills_count" }
   ]
  },
  {
   "title": "node number currently in memory",
   "type": "graph",
   "description": "The number of nodes currently in memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_nodes_count" }
   ]
  },
  {
   "title": "employee node number currently in memory",
   "type": "graph",
   "description": "The number of employee nodes currently in memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_stats_employees_count" }
   ]
  },
  {
   "title": "security total errors number",
   "type": "graph",
   "description": "The total number of security errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsk_security_errors_count" }
   ]
  }
 ]
}